version: "3.9"  # optional since v1.27.0
services:
  backend:
    build: backend
    image: backend:latest
    ports:
      - "8082:8000"
  dash_app:
    build: dash_app
    image: dash_app:latest
    ports:
      - "8050:8000"
  frontend:
    build: frontend
    image: frontend:latest
    ports:
      - "80:80"
